Repository kubernetes/publishing-bot, pull requests merged in 2018-11, with the labels that each got.

#129 Override end-of-line attributes in gitattributes files
  artifacts/scripts/construct.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#128 Remove travis in favor of Prow
  .travis.yml
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#130 Recheckout when text conversion mode is changed
  artifacts/scripts/construct.sh
  cmd/publishing-bot/publisher.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#131 Bump default go version to 1.11.2
  cmd/init-repo/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#132 Add 1.13 branches and disable publishing of 1.9
  configs/kubernetes-rules-configmap.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#134 Fix bug: shell syntax error
  artifacts/scripts/construct.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#137 Add mfojtik and nikhita as reviewers
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#136 Fix typo: corresonding -> corresponding
  cmd/collapsed-kube-commit-mapper/main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS
