Repository kubernetes/publishing-bot, pull requests merged in 2018-06, with the labels that each got.

#66 Create SECURITY_CONTACTS
  SECURITY_CONTACTS
Labels: cncf-cla: yes, lgtm, size/S

#62 Keep 7 days full log history in (rotated) run.log
  Gopkg.lock
  Gopkg.toml
  cmd/publishing-bot/publisher.go
  cmd/publishing-bot/publisher_logger.go
  vendor/gopkg.in/natefinch/lumberjack.v2/.gitignore
  vendor/gopkg.in/natefinch/lumberjack.v2/LICENSE
  vendor/gopkg.in/natefinch/lumberjack.v2/README.md
  vendor/gopkg.in/natefinch/lumberjack.v2/chown.go
  vendor/gopkg.in/natefinch/lumberjack.v2/chown_linux.go
  vendor/gopkg.in/natefinch/lumberjack.v2/lumberjack.go
Labels: cncf-cla: yes, lgtm, size/XL

#67 Add 1.11 branches
  configs/kubernetes-rules-configmap.yaml
Labels: cncf-cla: yes, lgtm, size/L

#68 Remove Gopkg.toml file
  configs/kubernetes-rules-configmap.yaml
Labels: cncf-cla: yes, size/XS

#69 Replace non-existing clone flag --no-tags in git 2.1.4 with bash tag removal
  cmd/publishing-bot/publisher.go
Labels: cncf-cla: yes, lgtm, size/S
