Repository kubernetes/publishing-bot, pull requests merged in 2018-09, with the labels that each got.

#93 Add csi-api repo to publish bot
  configs/kubernetes-rules-configmap.yaml
  hack/fetch-all-latest-and-push.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#96 Handle branching points for new branches which do not contain subdir
  artifacts/scripts/util.sh
Labels: approved, cncf-cla: yes, kind/bug, lgtm, priority/important-soon, size/S

#98 Fix SKIP_TAGS logic
  artifacts/scripts/construct.sh
Labels: approved, cncf-cla: yes, lgtm, priority/critical-urgent, size/XS

#101 Speed up if nothing changed on a branch
  artifacts/scripts/construct.sh
  cmd/publishing-bot/publisher.go
  cmd/sync-tags/main.go
  configs/kubernetes-rules-configmap.yaml
  hack/fetch-all-latest-and-push.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#102 Fix rules typo
  artifacts/scripts/util.sh
  configs/kubernetes-rules-configmap.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#104 Delete new Godeps file not on the branch
  artifacts/scripts/util.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#103 Clean up updateSourceRepo and checkout branch before rule loading
  artifacts/scripts/construct.sh
  artifacts/scripts/util.sh
  cmd/publishing-bot/publisher.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#105 Fix source repo remote branch loop
  cmd/publishing-bot/publisher.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#108 Fix kube-controller-manager repo to point to its staging dir
  configs/kubernetes-rules-configmap.yaml
Labels: approved, cncf-cla: yes, lgtm, priority/critical-urgent, size/XS

#106 Fix go-git ref name
  cmd/publishing-bot/publisher.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#107 Speed-up branch fetch by not deleting remote first
  artifacts/scripts/construct.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#109 Speed-up no-op tagging
  cmd/sync-tags/main.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#110 Fix branch-name-hash map to be used on publish
  cmd/publishing-bot/publisher.go
Labels: approved, cncf-cla: yes, lgtm, priority/important-soon, size/XS

#111 sync-tags: support speed-up for annotated and non-annotated tags
  cmd/sync-tags/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#112 Misc fixes
  artifacts/scripts/construct.sh
  cmd/publishing-bot/publisher.go
  cmd/sync-tags/main.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#113 Add apiextensions as a dependency to csi-api
  configs/kubernetes-rules-configmap.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#114 sync-tags: make post-failure debugging easier
  Makefile
  artifacts/scripts/construct.sh
  cmd/sync-tags/main.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#115 sync-tags: fix mapping file output
  cmd/sync-tags/main.go
  cmd/sync-tags/main_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M
