Repository kubernetes/publishing-bot, pull requests merged in 2018-10, with the labels that each got.

#116 Fix merge point calculation for repeated merges with same branch commit
  pkg/git/mainline.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#89 added bootstrap repo.
  configs/kubernetes-rules-configmap.yaml
  hack/fetch-all-latest-and-push.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#118 Revert "added bootstrap repo."
  configs/kubernetes-rules-configmap.yaml
  hack/fetch-all-latest-and-push.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#120 Bump default go version to 1.11.1
  .travis.yml
  cmd/init-repo/main.go
  configs/kubernetes-rules-configmap.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#121 Add cloud-provider repo
  configs/kubernetes-rules-configmap.yaml
  hack/fetch-all-latest-and-push.sh
Labels: cncf-cla: yes, lgtm, size/S

#122 Bump go-git to official release 4.7.1
  Gopkg.lock
  Gopkg.toml
  vendor/gopkg.in/src-d/go-git.v4/.travis.yml
  vendor/gopkg.in/src-d/go-git.v4/blame.go
  vendor/gopkg.in/src-d/go-git.v4/config/refspec.go
  vendor/gopkg.in/src-d/go-git.v4/go.mod
  vendor/gopkg.in/src-d/go-git.v4/go.sum
  vendor/gopkg.in/src-d/go-git.v4/object_walker.go
  vendor/gopkg.in/src-d/go-git.v4/options.go
  vendor/gopkg.in/src-d/go-git.v4/plumbing/cache/buffer_lru.go
  vendor/gopkg.in/src-d/go-git.v4/plumbing/cache/object_lru.go
  vendor/gopkg.in/src-d/go-git.v4/plumbing/format/diff/unified_encoder.go
  vendor/gopkg.in/src-d/go-git.v4/plumbing/format/index/decoder.go
  vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile/packfile.go
  vendor/gopkg.in/src-d/go-git.v4/plumbing/object/commit.go
  vendor/gopkg.in/src-d/go-git.v4/plumbing/object/commit_walker_file.go
  vendor/gopkg.in/src-d/go-git.v4/plumbing/object/tag.go
  vendor/gopkg.in/src-d/go-git.v4/plumbing/object/tree.go
  vendor/gopkg.in/src-d/go-git.v4/plumbing/storer/object.go
  vendor/gopkg.in/src-d/go-git.v4/plumbing/transport/server/loader.go
  vendor/gopkg.in/src-d/go-git.v4/plumbing/transport/ssh/auth_method.go
  vendor/gopkg.in/src-d/go-git.v4/prune.go
  vendor/gopkg.in/src-d/go-git.v4/references.go
  vendor/gopkg.in/src-d/go-git.v4/repository.go
  vendor/gopkg.in/src-d/go-git.v4/status.go
  vendor/gopkg.in/src-d/go-git.v4/storage/filesystem/dotgit/dotgit.go
  vendor/gopkg.in/src-d/go-git.v4/storage/filesystem/module.go
  vendor/gopkg.in/src-d/go-git.v4/storage/filesystem/object.go
  vendor/gopkg.in/src-d/go-git.v4/storage/filesystem/storage.go
  vendor/gopkg.in/src-d/go-git.v4/storage/memory/storage.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#123 Handle degenerated non-mainline merge
  artifacts/scripts/util.sh
Labels: approved, cncf-cla: yes, do-not-merge/hold, lgtm, size/XS

#124 Handle degenerated non-mainline merge - part 2
  artifacts/scripts/util.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS
