Repository kubernetes/publishing-bot, pull requests merged in 2018-08, with the labels that each got.

#78 Disable publishing of 1.8 and older
  configs/kubernetes-rules-configmap.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#80 Add branch rule go version value
  Dockerfile
  cmd/init-repo/main.go
  cmd/publishing-bot/config/rules.go
  cmd/publishing-bot/publisher.go
  cmd/publishing-bot/publisher_test.go
  configs/kubernetes-rules-configmap.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#81 Add memory request+limit config vars
  Makefile
  artifacts/manifests/podspec.yaml
  configs/example
  configs/kubernetes
Labels: approved, cncf-cla: yes, lgtm, size/S

#82 Report better logs for github issue
  cmd/publishing-bot/github.go
  cmd/publishing-bot/github_test.go
  cmd/publishing-bot/log_builder.go
  cmd/publishing-bot/log_builder_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#83 cmd/*: add github-host and package flag
  README.md
  artifacts/scripts/construct.sh
  artifacts/scripts/util.sh
  cmd/init-repo/main.go
  cmd/publishing-bot/config/config.go
  cmd/publishing-bot/main.go
  cmd/publishing-bot/publisher.go
  cmd/publishing-bot/server.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#85 Fix base package script passing
  artifacts/scripts/construct.sh
  artifacts/scripts/util.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#86 Tighten log stdout/err order via lineWriter & syncWriter
  cmd/publishing-bot/log_builder.go
  cmd/publishing-bot/publisher_logger.go
  cmd/publishing-bot/publisher_logger_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#87 init-repo: set Dir for go installation
  cmd/init-repo/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#88 Fixes missing license
  cmd/publishing-bot/publisher_logger_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#90 allow to skip tag synchronization
  artifacts/scripts/construct.sh
  cmd/publishing-bot/config/rules.go
  cmd/publishing-bot/publisher.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#91 run git gc --auto before syncing repos
  artifacts/scripts/construct.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#92 fix args count check
  artifacts/scripts/construct.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS
