Repository kubernetes/publishing-bot, pull requests merged in 2018-02, with the labels that each got.

#33 Update Godeps.json during tagging to point to tags
  artifacts/scripts/publish_template.sh
  cmd/sync-tags/godeps.go
  cmd/sync-tags/godeps_test.go
  cmd/sync-tags/main.go
Labels: cncf-cla: yes, size/L

#34 Switch publish script into smoke tests in rules yaml
  artifacts/scripts/construct.sh
  artifacts/scripts/publish_api.sh
  artifacts/scripts/publish_apiextensions_apiserver.sh
  artifacts/scripts/publish_apimachinery.sh
  artifacts/scripts/publish_apiserver.sh
  artifacts/scripts/publish_client_go.sh
  artifacts/scripts/publish_code_generator.sh
  artifacts/scripts/publish_kube_aggregator.sh
  artifacts/scripts/publish_metrics.sh
  artifacts/scripts/publish_sample_apiserver.sh
  artifacts/scripts/publish_sample_controller.sh
  cmd/publishing-bot/config/config.go
  cmd/publishing-bot/config/rules.go
  cmd/publishing-bot/main.go
  cmd/publishing-bot/publisher.go
  configs/kubernetes-rules-configmap.yaml
Labels: cncf-cla: yes, size/XL

#35 Add required-packages field to include code-generator
  artifacts/scripts/construct.sh
  artifacts/scripts/util.sh
  cmd/publishing-bot/config/rules.go
  cmd/publishing-bot/publisher.go
  configs/kubernetes-rules-configmap.yaml
Labels: cncf-cla: yes, size/L

#40 allow to fetch rules from URL
  cmd/init-repo/main.go
  cmd/publishing-bot/config/rules.go
  cmd/publishing-bot/main.go
  cmd/publishing-bot/publisher.go
Labels: cncf-cla: yes, lgtm, size/M

#39 Fix namespace in delete wait loop
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS

#42 Fix time of extra tag commit
  cmd/sync-tags/main.go
Labels: cncf-cla: yes, lgtm, priority/critical-urgent, size/XS

#44 fix rule loading
  cmd/publishing-bot/config/rules.go
Labels: cncf-cla: yes, size/XS

#43 Add 1.10 branches
  configs/kubernetes-rules-configmap.yaml
Labels: cncf-cla: yes, lgtm, priority/important-soon, size/L

#46 Cope with extra files in Godeps/ directory
  artifacts/scripts/util.sh
Labels: cncf-cla: yes, kind/bug, lgtm, priority/critical-urgent, size/XS

#48 Simplify is-merge check
  artifacts/scripts/util.sh
Labels: cncf-cla: yes, lgtm, size/S
