Repository kubernetes/publishing-bot, pull requests merged in 2018-07, with the labels that each got.

#70 Add requests+limits for memory and lower cpu requests
  artifacts/manifests/podspec.yaml
Labels: cncf-cla: yes, lgtm, size/S

#71 README: remove reporting issues from Known Issues
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#73 Add CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#74 Update to go 1.10.2
  Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#77 Fix 1.10 go cache
  artifacts/manifests/podspec.yaml
  configs/example-configmap.yaml
  configs/example-rules-configmap.yaml
  configs/kubernetes-configmap.yaml
  configs/kubernetes-rules-configmap.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S
