Repository kubernetes/publishing-bot, pull requests merged in 2018-04, with the labels that each got.

#56 Bump godep version to v80
  cmd/init-repo/main.go
Labels: cncf-cla: yes, lgtm, size/XS

#59 typo fix
  README.md
Labels: cncf-cla: yes, size/XS

#60 Indent godep output with tabs
  artifacts/scripts/util.sh
Labels: cncf-cla: yes, lgtm, size/S

#58 typo fix
  README.md
Labels: cncf-cla: yes, size/XS

#57 Grammatical errors
  README.md
Labels: cncf-cla: yes, size/XS

#61 Squash godep commits or skip all of them if nothing changed
  artifacts/scripts/util.sh
Labels: cncf-cla: yes, lgtm, size/M
