Repository kubernetes/publishing-bot, pull requests merged in 2019-01, with the labels that each got.

#140 Switch to ReplicaSet
  Makefile
  README.md
  artifacts/manifests/rs.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#143 Add rules validation
  Makefile
  cmd/init-repo/main.go
  cmd/publishing-bot/config/rules.go
  cmd/publishing-bot/publisher.go
  cmd/validate-rules/main.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#144 Fix publishing of component-base
  Dockerfile
  artifacts/scripts/construct.sh
  artifacts/scripts/util.sh
  cmd/collapsed-kube-commit-mapper/main.go
  cmd/init-repo/main.go
  configs/kubernetes-rules-configmap.yaml
  hack/fetch-all-latest-and-push.sh
  pkg/git/mainline.go
  pkg/git/mapping.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#146 util.sh: fix rev-parse typo
  artifacts/scripts/util.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#145 Add csi-translation-lib repo
  configs/kubernetes-rules-configmap.yaml
  hack/fetch-all-latest-and-push.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#149 Fix smoke test old-HEAD vs. new-HEAD comparison
  cmd/publishing-bot/publisher.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#150 Increase memory limits to survive smoke-test
  configs/kubernetes
Labels: approved, cncf-cla: yes, lgtm, size/XS

#151 rules: add component-base dep to apiextensions-apiserver and kubelet
  configs/kubernetes-rules-configmap.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#148 configs: get kubernetes rules from k/k repo
  Makefile
  artifacts/manifests/podspec.yaml
  configs/example-configmap.yaml
  configs/kubernetes-configmap.yaml
  configs/kubernetes-nightly-configmap.yaml
  configs/kubernetes-rules-configmap.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#154 Fix deployment with rules from the repo
  Makefile
  configs/kubernetes-rules-configmap.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#153 Skip godeps generation for commits containing incorrect godep changes
  artifacts/scripts/util.sh
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S
