Repository kubernetes/publishing-bot, pull requests merged in 2019-06, with the labels that each got.

#182 Add new staging repo: kubectl
  hack/fetch-all-latest-and-push.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#183 Enable sync-tags only for main publishing-bot
  Dockerfile
  Makefile
  artifacts/scripts/construct.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#184 sync-tags: add gomodules support
  artifacts/scripts/construct.sh
  cmd/sync-tags/godeps.go
  cmd/sync-tags/gomod.go
  cmd/sync-tags/main.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#185 Fix go mod publishing
  Dockerfile
  Makefile
  artifacts/scripts/util.sh
  cmd/gomod-zip/zip.go
  cmd/sync-tags/gomod.go
  cmd/sync-tags/main.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#188 Cope with undefined PUBLISHER_BOT_GENERATE_GODEPS
  artifacts/scripts/construct.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#189 Add missing copyright boilerplate headers
  Makefile
  cmd/godeps-gen/main.go
  cmd/init-repo/main.go
Labels: approved, cncf-cla: yes, lgtm, size/M, ¯\_(ツ)_/¯

#190 Fix sync-tags --generate-godeps syntax error
  artifacts/scripts/construct.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS
