Repository kubernetes/publishing-bot, pull requests merged in 2019-04, with the labels that each got.

#172 Switch branch to godeps rules file and issue
  configs/kubernetes-godeps
  configs/kubernetes-godeps-configmap.yaml
  configs/kubernetes-godeps-rules-configmap.yaml
  configs/kubernetes-godeps-token
Labels: approved, cncf-cla: yes, lgtm, size/XS

#173 Change godeps Docker image
  configs/kubernetes-godeps
Labels: approved, cncf-cla: yes, lgtm, size/XS

#174 Fix waitFor calculation
  cmd/publishing-bot/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#175 Cherry-pick of #174: Fix waitFor calculation
  cmd/publishing-bot/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#169 go-mod support
  .editorconfig
  Dockerfile
  Makefile
  README.md
  artifacts/scripts/construct.sh
  artifacts/scripts/util.sh
  cmd/godeps-gen/main.go
  cmd/init-repo/main.go
  cmd/publishing-bot/config/rules.go
  cmd/publishing-bot/publisher.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#168 Bump to private branch to display more info in error messages
  Gopkg.lock
  Gopkg.toml
  vendor/gopkg.in/src-d/go-git.v4/storage/filesystem/dotgit/dotgit.go
  vendor/gopkg.in/src-d/go-git.v4/storage/filesystem/dotgit/dotgit_setref.go
  vendor/gopkg.in/src-d/go-git.v4/storage/memory/storage.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#176 Add new staging repo: legacy-cloud-providers
  hack/fetch-all-latest-and-push.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS
