Repository kubernetes/publishing-bot, pull requests merged in 2019-02, with the labels that each got.

#157 Move golang download to construction time
  Makefile
  cmd/init-repo/main.go
  cmd/publishing-bot/install_golang.go
  cmd/publishing-bot/publisher.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#160 Update to go-git.v4 4.9.1
  Gopkg.lock
  Gopkg.toml
  vendor/gopkg.in/src-d/go-git.v4/options.go
  vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile/common.go
  vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile/fsobject.go
  vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile/packfile.go
  vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile/parser.go
  vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile/scanner.go
  vendor/gopkg.in/src-d/go-git.v4/plumbing/object/commit_walker.go
  vendor/gopkg.in/src-d/go-git.v4/plumbing/object/commit_walker_file.go
  vendor/gopkg.in/src-d/go-git.v4/repository.go
  vendor/gopkg.in/src-d/go-git.v4/storage/filesystem/dotgit/dotgit_setref.go
  vendor/gopkg.in/src-d/go-git.v4/storage/filesystem/dotgit/dotgit_setref_norwfs.go
  vendor/gopkg.in/src-d/go-git.v4/storage/filesystem/object.go
  vendor/gopkg.in/src-d/go-git.v4/storage/filesystem/storage.go
Labels: cncf-cla: yes, lgtm, size/XL

#161 Make validate-rules command a bit more verbose
  cmd/publishing-bot/config/rules.go
  cmd/validate-rules/main.go
Labels: cncf-cla: yes, lgtm, size/S

#158 Fixes for running kubernetes-nightly config in CNCF cluster
  artifacts/scripts/construct.sh
  cmd/init-repo/main.go
  cmd/publishing-bot/publisher.go
  cmd/sync-tags/main.go
  configs/kubernetes-nightly
  configs/kubernetes-nightly-configmap.yaml
  configs/kubernetes-nightly-rules-configmap.yaml
  pkg/golang/install.go
Labels: cncf-cla: yes, lgtm, size/M
