Repository kubernetes/publishing-bot, pull requests merged in 2019-07, with the labels that each got.

#191 [godeps] Use kubernetes' forked version of godep
  cmd/init-repo/main.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#193 Run sync-tags on godeps branch
  Dockerfile
  Makefile
  artifacts/scripts/construct.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#197 Bump default Go version to 1.12.7
  pkg/golang/install.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#199 Use gcr.io/k8s-staging-publishing-bot for storing godeps image
  configs/kubernetes-godeps
Labels: approved, cncf-cla: yes, lgtm, size/XS

#198 Use gcr.io/k8s-staging-publishing-bot for storing image
  configs/kubernetes
Labels: approved, cncf-cla: yes, lgtm, size/XS

#200 Add nikhita to git-crypt
  .git-crypt/keys/default/0/2583D03F747BF75DA761DAC4565C11F0FFCFA4EC.gpg
Labels: approved, cncf-cla: yes, lgtm, size/XS
