Repository kubernetes/publishing-bot, pull requests merged in 2020-07, with the labels that each got.

#231 util.sh: avoid side-effect from go mod download in dependencies
  artifacts/scripts/util.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#232 Move default go version to rules file
  cmd/init-repo/main.go
  cmd/publishing-bot/config/rules.go
  pkg/golang/install.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#233 Add repo SECURITY.md
  SECURITY.md
Labels: approved, cncf-cla: yes, lgtm, size/S
