Repository kubernetes/publishing-bot, pull requests merged in 2020-06, with the labels that each got.

#226 scripts: update sed separator to be `,`
  artifacts/scripts/util.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#227 sync-tags: run go mod tidy after updating deps in go.mod
  cmd/sync-tags/gomod.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#228 sync-tags: use go-git for fetching tags
  cmd/sync-tags/main.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#230 Bump default go version to 1.14.4
  pkg/golang/install.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
