Repository kubernetes/publishing-bot, pull requests merged in 2021-03, with the labels that each got.

#246 update regex to match some special case (ie 1.15.10)
  cmd/publishing-bot/config/rules.go
  cmd/publishing-bot/config/rules_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, priority/critical-urgent, size/S

#249 tests: add makefile rule to run go tests
  .gitignore
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#251 Allow specifying branch-specific smoke tests
  cmd/publishing-bot/config/rules.go
  cmd/publishing-bot/publisher.go
Labels: approved, cncf-cla: yes, lgtm, size/M
