Repository kubernetes/publishing-bot, pull requests merged in 2021-12, with the labels that each got.

#269 Choose only one dst branch point commit for specified k/k commits
  artifacts/scripts/util.sh
Labels: size/M, cncf-cla: yes, lgtm, approved

#267 Update Dockerfile to newest git version for debian:stretch
  Dockerfile
Labels: cncf-cla: yes, lgtm, size/XS, approved

#268 Post results to issues in kubernetes-nightly/kubernetes repo
  configs/kubernetes-nightly-configmap.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#270 Check if the directories are actually present in k8s branches
  cmd/validate-rules/main.go
  cmd/validate-rules/staging/github_utils.go
  cmd/validate-rules/staging/validate.go
  go.sum
Labels: cncf-cla: yes, lgtm, approved, size/L

#271 OWNERS: Add Release Engineering reviewers
  OWNERS
  OWNERS_ALIASES
  SECURITY_CONTACTS
Labels: size/M, cncf-cla: yes, lgtm, approved

#273 Add GCB config for image building
  Makefile
  cloudbuild.yaml
Labels: size/M, cncf-cla: yes, lgtm, approved

#276 .github: Add dependabot config
  .github/dependabot.yml
Labels: cncf-cla: yes, lgtm, size/S, approved

#278 Script to fork/create repositories needed by publishing-bot
  hack/create-repos.sh
  hack/fetch-all-latest-and-push.sh
  hack/repos.sh
Labels: cncf-cla: yes, lgtm, approved, size/L

#279 update README to match new scripts
  README.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#274 Lint all the things
  .golangci.yml
  cmd/collapsed-kube-commit-mapper/main.go
  cmd/gomod-zip/zip.go
  cmd/init-repo/main.go
  cmd/publishing-bot/config/rules.go
  cmd/publishing-bot/config/rules_test.go
  cmd/publishing-bot/github.go
  cmd/publishing-bot/log_builder.go
  cmd/publishing-bot/log_builder_test.go
  cmd/publishing-bot/main.go
  cmd/publishing-bot/publisher.go
  cmd/publishing-bot/publisher_logger.go
  cmd/publishing-bot/publisher_logger_test.go
  cmd/publishing-bot/publisher_test.go
  cmd/publishing-bot/server.go
  cmd/sync-tags/gomod.go
  cmd/sync-tags/main.go
  cmd/validate-rules/main.go
  cmd/validate-rules/staging/github_utils.go
  cmd/validate-rules/staging/validate.go
  hack/verify-golangci-lint.sh
  pkg/git/mapping.go
  pkg/golang/install.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#250 go.mod: Update module to go1.17 and fix lithammer/dedent import
  cmd/sync-tags/main.go
  go.mod
  go.sum
Labels: size/M, cncf-cla: yes, lgtm, approved

#282 OWNERS_ALIASES: promote palnabarun to a Release Manager
  OWNERS_ALIASES
Labels: cncf-cla: yes, lgtm, size/XS, approved

#283 Add instructions for updating rules
  README.md
Labels: cncf-cla: yes, lgtm, size/S, approved
