Repository kubernetes/publishing-bot, pull requests merged in 2023-04, with the labels that each got.

#338 Switched from N1 to E2 machine
  cloudbuild.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#339 Add akhilerm as reviewer
  OWNERS
Labels: cncf-cla: yes, lgtm, size/XS, approved

#334 add scripts to run/test publishing-bot locally
  test/k8s-gen-bot-config.sh
  test/run-bot-local.sh
Labels: cncf-cla: yes, lgtm, approved, size/L

#342 return the correct exit code when publisher fails
  cmd/publishing-bot/main.go
Labels: cncf-cla: yes, lgtm, size/S, approved
